In [7]:
import csv
import os
import mysql.connector

In [8]:
mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="NewStrongPassword123!"  # use the password you set
)

print("Connected successfully!")

Connected successfully!

In [9]:
# Create a cursor object
mycursor = mydb.cursor()

# Run only once: Create the database if it doesn't exist
mycursor.execute("CREATE DATABASE IF NOT EXISTS ecommerce")

print("Database created or already exists.")

Database created or already exists.

In [10]:
# Add password parameter if needed
mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="NewStrongPassword123!",
    database="ecommerce"
)
mycursor = mydb.cursor()

In [11]:
import pandas as pd
import os

# Your data folder
folder_path = "/Users/sathvikvadlapatla/Downloads/Langchain Chatbot/data"

# List of CSV files = table names
table_names = [
    "distribution_centers",
    "events",
    "inventory_items",
    "order_items",
    "orders",
    "products",
    "users"
]

# Function to map pandas dtype to MySQL type
def map_dtype_to_mysql(dtype):
    if pd.api.types.is_integer_dtype(dtype):
        return "INT"
    elif pd.api.types.is_float_dtype(dtype):
        return "FLOAT"
    elif pd.api.types.is_datetime64_any_dtype(dtype):
        return "TIMESTAMP"
    else:
        return "VARCHAR(255)"  # default to string

# Loop through all CSVs
for table_name in table_names:
    file_path = os.path.join(folder_path, f"{table_name}.csv")
    df = pd.read_csv(file_path)

    print(f"\n📁 TABLE: `{table_name}`")
    print("🧾 Columns & Inferred MySQL Types:")

    create_columns = []
    for col in df.columns:
        col_type = map_dtype_to_mysql(df[col])
        print(f"  - {col}: {col_type}")
        create_columns.append(f"`{col}` {col_type}")

    create_stmt = f"CREATE TABLE `{table_name}` (\n  " + ",\n  ".join(create_columns) + "\n);"
    print("\n🛠️ SQL to create table:")
    print(create_stmt)
    print("─" * 60)

📁 TABLE: `distribution_centers`
🧾 Columns & Inferred MySQL Types:
  - id: INT
  - name: VARCHAR(255)
  - latitude: FLOAT
  - longitude: FLOAT

🛠️ SQL to create table:
CREATE TABLE `distribution_centers` (
  `id` INT,
  `name` VARCHAR(255),
  `latitude` FLOAT,
  `longitude` FLOAT
);
────────────────────────────────────────────────────────────

📁 TABLE: `events`
🧾 Columns & Inferred MySQL Types:
  - id: INT
  - user_id: FLOAT
  - sequence_number: INT
  - session_id: VARCHAR(255)
  - created_at: VARCHAR(255)
  - ip_address: VARCHAR(255)
  - city: VARCHAR(255)
  - state: VARCHAR(255)
  - postal_code: VARCHAR(255)
  - browser: VARCHAR(255)
  - traffic_source: VARCHAR(255)
  - uri: VARCHAR(255)
  - event_type: VARCHAR(255)

🛠️ SQL to create table:
CREATE TABLE `events` (
  `id` INT,
  `user_id` FLOAT,
  `sequence_number` INT,
  `session_id` VARCHAR(255),
  `created_at` VARCHAR(255),
  `ip_address` VARCHAR(255),
  `city` VARCHAR(255),
  `state` VARCHAR(255),
  `postal_code` VARCHAR(255),
  `browser` VARCHAR(255),
  `traffic_source` VARCHAR(255),
  `uri` VARCHAR(255),
  `event_type` VARCHAR(255)
);
────────────────────────────────────────────────────────────

📁 TABLE: `inventory_items`
🧾 Columns & Inferred MySQL Types:
  - id: INT
  - product_id: INT
  - created_at: VARCHAR(255)
  - sold_at: VARCHAR(255)
  - cost: FLOAT
  - product_category: VARCHAR(255)
  - product_name: VARCHAR(255)
  - product_brand: VARCHAR(255)
  - product_retail_price: FLOAT
  - product_department: VARCHAR(255)
  - product_sku: VARCHAR(255)
  - product_distribution_center_id: INT

🛠️ SQL to create table:
CREATE TABLE `inventory_items` (
  `id` INT,
  `product_id` INT,
  `created_at` VARCHAR(255),
  `sold_at` VARCHAR(255),
  `cost` FLOAT,
  `product_category` VARCHAR(255),
  `product_name` VARCHAR(255),
  `product_brand` VARCHAR(255),
  `product_retail_price` FLOAT,
  `product_department` VARCHAR(255),
  `product_sku` VARCHAR(255),
  `product_distribution_center_id` INT
);
────────────────────────────────────────────────────────────

📁 TABLE: `order_items`
🧾 Columns & Inferred MySQL Types:
  - id: INT
  - order_id: INT
  - user_id: INT
  - product_id: INT
  - inventory_item_id: INT
  - status: VARCHAR(255)
  - created_at: VARCHAR(255)
  - shipped_at: VARCHAR(255)
  - delivered_at: VARCHAR(255)
  - returned_at: VARCHAR(255)
  - sale_price: FLOAT

🛠️ SQL to create table:
CREATE TABLE `order_items` (
  `id` INT,
  `order_id` INT,
  `user_id` INT,
  `product_id` INT,
  `inventory_item_id` INT,
  `status` VARCHAR(255),
  `created_at` VARCHAR(255),
  `shipped_at` VARCHAR(255),
  `delivered_at` VARCHAR(255),
  `returned_at` VARCHAR(255),
  `sale_price` FLOAT
);
────────────────────────────────────────────────────────────

📁 TABLE: `orders`
🧾 Columns & Inferred MySQL Types:
  - order_id: INT
  - user_id: INT
  - status: VARCHAR(255)
  - gender: VARCHAR(255)
  - created_at: VARCHAR(255)
  - returned_at: VARCHAR(255)
  - shipped_at: VARCHAR(255)
  - delivered_at: VARCHAR(255)
  - num_of_item: INT

🛠️ SQL to create table:
CREATE TABLE `orders` (
  `order_id` INT,
  `user_id` INT,
  `status` VARCHAR(255),
  `gender` VARCHAR(255),
  `created_at` VARCHAR(255),
  `returned_at` VARCHAR(255),
  `shipped_at` VARCHAR(255),
  `delivered_at` VARCHAR(255),
  `num_of_item` INT
);
────────────────────────────────────────────────────────────

📁 TABLE: `products`
🧾 Columns & Inferred MySQL Types:
  - id: INT
  - cost: FLOAT
  - category: VARCHAR(255)
  - name: VARCHAR(255)
  - brand: VARCHAR(255)
  - retail_price: FLOAT
  - department: VARCHAR(255)
  - sku: VARCHAR(255)
  - distribution_center_id: INT

🛠️ SQL to create table:
CREATE TABLE `products` (
  `id` INT,
  `cost` FLOAT,
  `category` VARCHAR(255),
  `name` VARCHAR(255),
  `brand` VARCHAR(255),
  `retail_price` FLOAT,
  `department` VARCHAR(255),
  `sku` VARCHAR(255),
  `distribution_center_id` INT
);
────────────────────────────────────────────────────────────

📁 TABLE: `users`
🧾 Columns & Inferred MySQL Types:
  - id: INT
  - first_name: VARCHAR(255)
  - last_name: VARCHAR(255)
  - email: VARCHAR(255)
  - age: INT
  - gender: VARCHAR(255)
  - state: VARCHAR(255)
  - street_address: VARCHAR(255)
  - postal_code: VARCHAR(255)
  - city: VARCHAR(255)
  - country: VARCHAR(255)
  - latitude: FLOAT
  - longitude: FLOAT
  - traffic_source: VARCHAR(255)
  - created_at: VARCHAR(255)

🛠️ SQL to create table:
CREATE TABLE `users` (
  `id` INT,
  `first_name` VARCHAR(255),
  `last_name` VARCHAR(255),
  `email` VARCHAR(255),
  `age` INT,
  `gender` VARCHAR(255),
  `state` VARCHAR(255),
  `street_address` VARCHAR(255),
  `postal_code` VARCHAR(255),
  `city` VARCHAR(255),
  `country` VARCHAR(255),
  `latitude` FLOAT,
  `longitude` FLOAT,
  `traffic_source` VARCHAR(255),
  `created_at` VARCHAR(255)
);
────────────────────────────────────────────────────────────

In [12]:
create_table_queries = {
    "distribution_centers": """
        CREATE TABLE IF NOT EXISTS distribution_centers (
            id INT,
            name VARCHAR(255),
            latitude FLOAT,
            longitude FLOAT
        )
    """,
    "events": """
        CREATE TABLE IF NOT EXISTS events (
            id INT,
            user_id FLOAT,
            sequence_number INT,
            session_id VARCHAR(255),
            created_at VARCHAR(255),
            ip_address VARCHAR(255),
            city VARCHAR(255),
            state VARCHAR(255),
            postal_code VARCHAR(255),
            browser VARCHAR(255),
            traffic_source VARCHAR(255),
            uri VARCHAR(255),
            event_type VARCHAR(255)
        )
    """,
    "inventory_items": """
        CREATE TABLE IF NOT EXISTS inventory_items (
            id INT,
            product_id INT,
            created_at VARCHAR(255),
            sold_at VARCHAR(255),
            cost FLOAT,
            product_category VARCHAR(255),
            product_name VARCHAR(255),
            product_brand VARCHAR(255),
            product_retail_price FLOAT,
            product_department VARCHAR(255),
            product_sku VARCHAR(255),
            product_distribution_center_id INT
        )
    """,
    "order_items": """
        CREATE TABLE IF NOT EXISTS order_items (
            id INT,
            order_id INT,
            user_id INT,
            product_id INT,
            inventory_item_id INT,
            status VARCHAR(255),
            created_at VARCHAR(255),
            shipped_at VARCHAR(255),
            delivered_at VARCHAR(255),
            returned_at VARCHAR(255),
            sale_price FLOAT
        )
    """,
    "orders": """
        CREATE TABLE IF NOT EXISTS orders (
            order_id INT,
            user_id INT,
            status VARCHAR(255),
            gender VARCHAR(255),
            created_at VARCHAR(255),
            returned_at VARCHAR(255),
            shipped_at VARCHAR(255),
            delivered_at VARCHAR(255),
            num_of_item INT
        )
    """,
    "products": """
        CREATE TABLE IF NOT EXISTS products (
            id INT,
            cost FLOAT,
            category VARCHAR(255),
            name VARCHAR(255),
            brand VARCHAR(255),
            retail_price FLOAT,
            department VARCHAR(255),
            sku VARCHAR(255),
            distribution_center_id INT
        )
    """,
    "users": """
        CREATE TABLE IF NOT EXISTS users (
            id INT,
            first_name VARCHAR(255),
            last_name VARCHAR(255),
            email VARCHAR(255),
            age INT,
            gender VARCHAR(255),
            state VARCHAR(255),
            street_address VARCHAR(255),
            postal_code VARCHAR(255),
            city VARCHAR(255),
            country VARCHAR(255),
            latitude FLOAT,
            longitude FLOAT,
            traffic_source VARCHAR(255),
            created_at VARCHAR(255)
        )
    """
}

# Execute the table creation queries
for table, query in create_table_queries.items():
    print(f"Creating table `{table}`...")
    mycursor.execute(f"DROP TABLE IF EXISTS {table}")
    mycursor.execute(query)
    print(f"✅ `{table}` created successfully.\n")

mydb.commit()

Creating table `distribution_centers`...
✅ `distribution_centers` created successfully.

Creating table `events`...
✅ `events` created successfully.

Creating table `inventory_items`...
✅ `inventory_items` created successfully.

Creating table `order_items`...
✅ `order_items` created successfully.

Creating table `orders`...
✅ `orders` created successfully.

Creating table `products`...
✅ `products` created successfully.

Creating table `users`...
✅ `users` created successfully.

In [13]:
import csv

# Reuse your existing connection and cursor: mydb, mycursor
folder_path = "/Users/sathvikvadlapatla/Downloads/Langchain Chatbot/data"
table_names = ["distribution_centers", "events", "inventory_items", "order_items", "orders", "products", "users"]

for table_name in table_names:
    file_path = os.path.join(folder_path, f"{table_name}.csv")
    
    print(f"\n📥 Inserting data into `{table_name}` from {file_path}")
    
    with open(file_path, "r", encoding="utf-8") as file:
        csv_data = csv.reader(file)
        headers = next(csv_data)  # skip header
        
        placeholders = ','.join(['%s'] * len(headers))
        insert_query = f"INSERT INTO {table_name} VALUES ({placeholders})"
        
        row_count = 0
        for row in csv_data:
            cleaned_row = [None if cell == '' else cell.replace(" UTC", "") for cell in row]
            try:
                mycursor.execute(insert_query, cleaned_row)
                row_count += 1
                if row_count % 10000 == 0:
                    print(f"  ↪ {row_count} rows inserted...")
            except mysql.connector.Error as err:
                print(f"  ❌ Error on row {row_count + 1}: {err}")
    
    mydb.commit()
    print(f"✅ Finished inserting {row_count} rows into `{table_name}`")

📥 Inserting data into `distribution_centers` from /Users/sathvikvadlapatla/Downloads/Langchain Chatbot/data/distribution_centers.csv
✅ Finished inserting 10 rows into `distribution_centers`

📥 Inserting data into `events` from /Users/sathvikvadlapatla/Downloads/Langchain Chatbot/data/events.csv
  ↪ 10000 rows inserted...
  ↪ 20000 rows inserted...
  ↪ 30000 rows inserted...
  ↪ 40000 rows inserted...
  ↪ 50000 rows inserted...
  ↪ 60000 rows inserted...
  ↪ 70000 rows inserted...
  ↪ 80000 rows inserted...
  ↪ 90000 rows inserted...
  ↪ 100000 rows inserted...
  ↪ 110000 rows inserted...
  ↪ 120000 rows inserted...
  ↪ 130000 rows inserted...
  ↪ 140000 rows inserted...
  ↪ 150000 rows inserted...
  ↪ 160000 rows inserted...
  ↪ 170000 rows inserted...
  ↪ 180000 rows inserted...
  ↪ 190000 rows inserted...
  ↪ 200000 rows inserted...
  ↪ 210000 rows inserted...
  ↪ 220000 rows inserted...
  ↪ 230000 rows inserted...
  ↪ 240000 rows inserted...
  ↪ 250000 rows inserted...
  ↪ 260000 rows inserted...
  ↪ 270000 rows inserted...
  ↪ 280000 rows inserted...
  ↪ 290000 rows inserted...
  ↪ 300000 rows inserted...
  ↪ 310000 rows inserted...
  ↪ 320000 rows inserted...
  ↪ 330000 rows inserted...
  ↪ 340000 rows inserted...
  ↪ 350000 rows inserted...
  ↪ 360000 rows inserted...
  ↪ 370000 rows inserted...
  ↪ 380000 rows inserted...
  ↪ 390000 rows inserted...
  ↪ 400000 rows inserted...
  ↪ 410000 rows inserted...
  ↪ 420000 rows inserted...
  ↪ 430000 rows inserted...
  ↪ 440000 rows inserted...
  ↪ 450000 rows inserted...
  ↪ 460000 rows inserted...
  ↪ 470000 rows inserted...
  ↪ 480000 rows inserted...
  ↪ 490000 rows inserted...
  ↪ 500000 rows inserted...
  ↪ 510000 rows inserted...
  ↪ 520000 rows inserted...
  ↪ 530000 rows inserted...
  ↪ 540000 rows inserted...
  ↪ 550000 rows inserted...
  ↪ 560000 rows inserted...
  ↪ 570000 rows inserted...
  ↪ 580000 rows inserted...
  ↪ 590000 rows inserted...
  ↪ 600000 rows inserted...
  ↪ 610000 rows inserted...
  ↪ 620000 rows inserted...
  ↪ 630000 rows inserted...
  ↪ 640000 rows inserted...
  ↪ 650000 rows inserted...
  ↪ 660000 rows inserted...
  ↪ 670000 rows inserted...
  ↪ 680000 rows inserted...
  ↪ 690000 rows inserted...
  ↪ 700000 rows inserted...
  ↪ 710000 rows inserted...
  ↪ 720000 rows inserted...
  ↪ 730000 rows inserted...
  ↪ 740000 rows inserted...
  ↪ 750000 rows inserted...
  ↪ 760000 rows inserted...
  ↪ 770000 rows inserted...
  ↪ 780000 rows inserted...
  ↪ 790000 rows inserted...
  ↪ 800000 rows inserted...
  ↪ 810000 rows inserted...
  ↪ 820000 rows inserted...
  ↪ 830000 rows inserted...
  ↪ 840000 rows inserted...
  ↪ 850000 rows inserted...
  ↪ 860000 rows inserted...
  ↪ 870000 rows inserted...
  ↪ 880000 rows inserted...
  ↪ 890000 rows inserted...
  ↪ 900000 rows inserted...
  ↪ 910000 rows inserted...
  ↪ 920000 rows inserted...
  ↪ 930000 rows inserted...
  ↪ 940000 rows inserted...
  ↪ 950000 rows inserted...
  ↪ 960000 rows inserted...
  ↪ 970000 rows inserted...
  ↪ 980000 rows inserted...
  ↪ 990000 rows inserted...
  ↪ 1000000 rows inserted...
  ↪ 1010000 rows inserted...
  ↪ 1020000 rows inserted...
  ↪ 1030000 rows inserted...
  ↪ 1040000 rows inserted...
  ↪ 1050000 rows inserted...
  ↪ 1060000 rows inserted...
  ↪ 1070000 rows inserted...
  ↪ 1080000 rows inserted...
  ↪ 1090000 rows inserted...
  ↪ 1100000 rows inserted...
  ↪ 1110000 rows inserted...
  ↪ 1120000 rows inserted...
  ↪ 1130000 rows inserted...
  ↪ 1140000 rows inserted...
  ↪ 1150000 rows inserted...
  ↪ 1160000 rows inserted...
  ↪ 1170000 rows inserted...
  ↪ 1180000 rows inserted...
  ↪ 1190000 rows inserted...
  ↪ 1200000 rows inserted...
  ↪ 1210000 rows inserted...
  ↪ 1220000 rows inserted...
  ↪ 1230000 rows inserted...
  ↪ 1240000 rows inserted...
  ↪ 1250000 rows inserted...
  ↪ 1260000 rows inserted...
  ↪ 1270000 rows inserted...
  ↪ 1280000 rows inserted...
  ↪ 1290000 rows inserted...
  ↪ 1300000 rows inserted...
  ↪ 1310000 rows inserted...
  ↪ 1320000 rows inserted...
  ↪ 1330000 rows inserted...
  ↪ 1340000 rows inserted...
  ↪ 1350000 rows inserted...
  ↪ 1360000 rows inserted...
  ↪ 1370000 rows inserted...
  ↪ 1380000 rows inserted...
  ↪ 1390000 rows inserted...
  ↪ 1400000 rows inserted...
  ↪ 1410000 rows inserted...
  ↪ 1420000 rows inserted...
  ↪ 1430000 rows inserted...
  ↪ 1440000 rows inserted...
  ↪ 1450000 rows inserted...
  ↪ 1460000 rows inserted...
  ↪ 1470000 rows inserted...
  ↪ 1480000 rows inserted...
  ↪ 1490000 rows inserted...
  ↪ 1500000 rows inserted...
  ↪ 1510000 rows inserted...
  ↪ 1520000 rows inserted...
  ↪ 1530000 rows inserted...
  ↪ 1540000 rows inserted...
  ↪ 1550000 rows inserted...
  ↪ 1560000 rows inserted...
  ↪ 1570000 rows inserted...
  ↪ 1580000 rows inserted...
  ↪ 1590000 rows inserted...
  ↪ 1600000 rows inserted...
  ↪ 1610000 rows inserted...
  ↪ 1620000 rows inserted...
  ↪ 1630000 rows inserted...
  ↪ 1640000 rows inserted...
  ↪ 1650000 rows inserted...
  ↪ 1660000 rows inserted...
  ↪ 1670000 rows inserted...
  ↪ 1680000 rows inserted...
  ↪ 1690000 rows inserted...
  ↪ 1700000 rows inserted...
  ↪ 1710000 rows inserted...
  ↪ 1720000 rows inserted...
  ↪ 1730000 rows inserted...
  ↪ 1740000 rows inserted...
  ↪ 1750000 rows inserted...
  ↪ 1760000 rows inserted...
  ↪ 1770000 rows inserted...
  ↪ 1780000 rows inserted...
  ↪ 1790000 rows inserted...
  ↪ 1800000 rows inserted...
  ↪ 1810000 rows inserted...
  ↪ 1820000 rows inserted...
  ↪ 1830000 rows inserted...
  ↪ 1840000 rows inserted...
  ↪ 1850000 rows inserted...
  ↪ 1860000 rows inserted...
  ↪ 1870000 rows inserted...
  ↪ 1880000 rows inserted...
  ↪ 1890000 rows inserted...
  ↪ 1900000 rows inserted...
  ↪ 1910000 rows inserted...
  ↪ 1920000 rows inserted...
  ↪ 1930000 rows inserted...
  ↪ 1940000 rows inserted...
  ↪ 1950000 rows inserted...
  ↪ 1960000 rows inserted...
  ↪ 1970000 rows inserted...
  ↪ 1980000 rows inserted...
  ↪ 1990000 rows inserted...
  ↪ 2000000 rows inserted...
  ↪ 2010000 rows inserted...
  ↪ 2020000 rows inserted...
  ↪ 2030000 rows inserted...
  ↪ 2040000 rows inserted...
  ↪ 2050000 rows inserted...
  ↪ 2060000 rows inserted...
  ↪ 2070000 rows inserted...
  ↪ 2080000 rows inserted...
  ↪ 2090000 rows inserted...
  ↪ 2100000 rows inserted...
  ↪ 2110000 rows inserted...
  ↪ 2120000 rows inserted...
  ↪ 2130000 rows inserted...
  ↪ 2140000 rows inserted...
  ↪ 2150000 rows inserted...
  ↪ 2160000 rows inserted...
  ↪ 2170000 rows inserted...
  ↪ 2180000 rows inserted...
  ↪ 2190000 rows inserted...
  ↪ 2200000 rows inserted...
  ↪ 2210000 rows inserted...
  ↪ 2220000 rows inserted...
  ↪ 2230000 rows inserted...
  ↪ 2240000 rows inserted...
  ↪ 2250000 rows inserted...
  ↪ 2260000 rows inserted...
  ↪ 2270000 rows inserted...
  ↪ 2280000 rows inserted...
  ↪ 2290000 rows inserted...
  ↪ 2300000 rows inserted...
  ↪ 2310000 rows inserted...
  ↪ 2320000 rows inserted...
  ↪ 2330000 rows inserted...
  ↪ 2340000 rows inserted...
  ↪ 2350000 rows inserted...
  ↪ 2360000 rows inserted...
  ↪ 2370000 rows inserted...
  ↪ 2380000 rows inserted...
  ↪ 2390000 rows inserted...
  ↪ 2400000 rows inserted...
  ↪ 2410000 rows inserted...
  ↪ 2420000 rows inserted...
✅ Finished inserting 2427931 rows into `events`

📥 Inserting data into `inventory_items` from /Users/sathvikvadlapatla/Downloads/Langchain Chatbot/data/inventory_items.csv
  ↪ 10000 rows inserted...
  ↪ 20000 rows inserted...
  ↪ 30000 rows inserted...
  ↪ 40000 rows inserted...
  ↪ 50000 rows inserted...
  ↪ 60000 rows inserted...
  ↪ 70000 rows inserted...
  ↪ 80000 rows inserted...
  ↪ 90000 rows inserted...
  ↪ 100000 rows inserted...
  ↪ 110000 rows inserted...
  ↪ 120000 rows inserted...
  ↪ 130000 rows inserted...
  ↪ 140000 rows inserted...
  ↪ 150000 rows inserted...
  ↪ 160000 rows inserted...
  ↪ 170000 rows inserted...
  ↪ 180000 rows inserted...
  ↪ 190000 rows inserted...
  ↪ 200000 rows inserted...
  ↪ 210000 rows inserted...
  ↪ 220000 rows inserted...
  ↪ 230000 rows inserted...
  ↪ 240000 rows inserted...
  ↪ 250000 rows inserted...
  ↪ 260000 rows inserted...
  ↪ 270000 rows inserted...
  ↪ 280000 rows inserted...
  ↪ 290000 rows inserted...
  ↪ 300000 rows inserted...
  ↪ 310000 rows inserted...
  ↪ 320000 rows inserted...
  ↪ 330000 rows inserted...
  ↪ 340000 rows inserted...
  ↪ 350000 rows inserted...
  ↪ 360000 rows inserted...
  ↪ 370000 rows inserted...
  ↪ 380000 rows inserted...
  ↪ 390000 rows inserted...
  ↪ 400000 rows inserted...
  ↪ 410000 rows inserted...
  ↪ 420000 rows inserted...
  ↪ 430000 rows inserted...
  ↪ 440000 rows inserted...
  ↪ 450000 rows inserted...
  ↪ 460000 rows inserted...
  ↪ 470000 rows inserted...
  ↪ 480000 rows inserted...
  ↪ 490000 rows inserted...
✅ Finished inserting 491098 rows into `inventory_items`

📥 Inserting data into `order_items` from /Users/sathvikvadlapatla/Downloads/Langchain Chatbot/data/order_items.csv
  ↪ 10000 rows inserted...
  ↪ 20000 rows inserted...
  ↪ 30000 rows inserted...
  ↪ 40000 rows inserted...
  ↪ 50000 rows inserted...
  ↪ 60000 rows inserted...
  ↪ 70000 rows inserted...
  ↪ 80000 rows inserted...
  ↪ 90000 rows inserted...
  ↪ 100000 rows inserted...
  ↪ 110000 rows inserted...
  ↪ 120000 rows inserted...
  ↪ 130000 rows inserted...
  ↪ 140000 rows inserted...
  ↪ 150000 rows inserted...
  ↪ 160000 rows inserted...
  ↪ 170000 rows inserted...
  ↪ 180000 rows inserted...
✅ Finished inserting 181891 rows into `order_items`

📥 Inserting data into `orders` from /Users/sathvikvadlapatla/Downloads/Langchain Chatbot/data/orders.csv
  ↪ 10000 rows inserted...
  ↪ 20000 rows inserted...
  ↪ 30000 rows inserted...
  ↪ 40000 rows inserted...
  ↪ 50000 rows inserted...
  ↪ 60000 rows inserted...
  ↪ 70000 rows inserted...
  ↪ 80000 rows inserted...
  ↪ 90000 rows inserted...
  ↪ 100000 rows inserted...
  ↪ 110000 rows inserted...
  ↪ 120000 rows inserted...
✅ Finished inserting 125530 rows into `orders`

📥 Inserting data into `products` from /Users/sathvikvadlapatla/Downloads/Langchain Chatbot/data/products.csv
  ↪ 10000 rows inserted...
  ↪ 20000 rows inserted...
✅ Finished inserting 29120 rows into `products`

📥 Inserting data into `users` from /Users/sathvikvadlapatla/Downloads/Langchain Chatbot/data/users.csv
  ↪ 10000 rows inserted...
  ↪ 20000 rows inserted...
  ↪ 30000 rows inserted...
  ↪ 40000 rows inserted...
  ↪ 50000 rows inserted...
  ↪ 60000 rows inserted...
  ↪ 70000 rows inserted...
  ↪ 80000 rows inserted...
  ↪ 90000 rows inserted...
  ↪ 100000 rows inserted...
✅ Finished inserting 100000 rows into `users`

In [23]:
import os
import warnings
warnings.filterwarnings('ignore')

from pydantic import BaseModel, Field, validator

from langchain.chains import LLMChain, LLMMathChain, SequentialChain, TransformChain
from langchain.llms import OpenAI
from langchain.output_parsers import PydanticOutputParser
from langchain.prompts import PromptTemplate
from langchain.tools import Tool

from langchain_openai import ChatOpenAI
from langchain.agents import AgentExecutor, create_openai_tools_agent, create_openai_functions_agent
from langchain_community.agent_toolkits import create_sql_agent, SQLDatabaseToolkit
from langchain_community.utilities import SQLDatabase
from langchain_community.agent_toolkits.sql.prompt import SQL_FUNCTIONS_SUFFIX

from langchain_core.messages import AIMessage, SystemMessage
from langchain_core.prompts.chat import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    MessagesPlaceholder,
)

from langchain import hub
from langchain_experimental.tools import PythonREPLTool
import subprocess

## SQL table connection

In [ ]:
# import urllib.parse

# password = urllib.parse.quote_plus("your#password")  # Replace "your#password" with your actual password
# sql_db = SQLDatabase.from_uri(f"mysql://root:{password}@localhost:3306/ecommerce")

# print(sql_db.dialect)
# print(sql_db.get_usable_table_names())
# sql_db.run("SELECT * FROM events LIMIT 10;")

In [24]:
import urllib.parse
from langchain_community.utilities import SQLDatabase

# Replace this with your actual MySQL password
raw_password = "NewStrongPassword123!"
password = urllib.parse.quote_plus(raw_password)

# MySQL connection string format
connection_uri = f"mysql+mysqlconnector://root:{password}@localhost:3306/ecommerce"

# Connect to the ecommerce database
sql_db = SQLDatabase.from_uri(connection_uri)

# Test connection
print("SQL Dialect:", sql_db.dialect)
print("Usable Tables:", sql_db.get_usable_table_names())

# Run a test query
print("\n Sample data from `events` table:")
print(sql_db.run("SELECT * FROM events LIMIT 5;"))

SQL Dialect: mysql
Usable Tables: ['distribution_centers', 'events', 'inventory_items', 'order_items', 'orders', 'products', 'users']

 Sample data from `events` table:
[(1679667, None, 3, 'ac0caa7c-cb18-4be3-9843-6e19b39e298b', '2020-04-01 08:44:00', '33.194.53.72', 'São Paulo', 'São Paulo', '02675-031', 'Firefox', 'Adwords', '/cancel', 'cancel'), (1405655, None, 3, 'eacfccad-fbe4-4326-b775-2b8d8c30e114', '2021-01-04 06:27:00', '46.34.135.113', 'São Paulo', 'São Paulo', '02675-031', 'Chrome', 'Adwords', '/cancel', 'cancel'), (1902445, None, 3, 'b907e002-1cae-4ac7-92b3-99442e7dc0fd', '2022-11-15 16:01:00', '101.59.93.62', 'São Paulo', 'São Paulo', '02675-031', 'Safari', 'Organic', '/cancel', 'cancel'), (1451379, None, 3, 'ce2eb56f-4657-4d1a-99cd-28fa3849e150', '2020-10-24 17:35:00', '52.128.145.141', 'São Paulo', 'São Paulo', '02675-031', 'Firefox', 'Email', '/cancel', 'cancel'), (1706107, None, 3, 'bfdcb2f0-6603-417d-9f94-d415cbd989c3', '2020-07-13 01:16:00', '192.195.224.31', 'São Paulo', 'São Paulo', '02675-031', 'Safari', 'Adwords', '/cancel', 'cancel')]

In [28]:
import os
from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate
from langchain_openai import ChatOpenAI  # Correct class for gpt-3.5-turbo

# Set API Key
os.environ['OPENAI_API_KEY'] = "Open_AI_Key"
# Define model
llm = ChatOpenAI(
    model_name="gpt-3.5-turbo-0125",
    temperature=0.0
)

In [ ]:
# Define prompt template
template1 = '''I want you to act as a financial advisor for people.
In an easy way, explain the basics of {financial_concept}.'''

prompt1 = PromptTemplate(
    input_variables=['financial_concept'],
    template=template1
)

# Create chain and run
chain1 = LLMChain(llm=llm, prompt=prompt1)
response = chain1.run('ESOPs')

print(response)

## Prompt Template 1: Act as a Role

In [ ]:
chain1.run('GDP')

## Prompt Template 2: Language Translation

In [ ]:
template2='''In an easy way translate the following sentence '{sentence}' into {target_language}'''

language_prompt = PromptTemplate(
    input_variables = ["sentence", "target_language"],
    template=template2
)

language_prompt.format(sentence="How are you", target_language='french')

chain2 = LLMChain(llm=llm,prompt=language_prompt)

In [ ]:
data = chain2({
    'sentence':"What is your name?",
    'target_language':'french'
})

print("English Sentence:", data['sentence'])
print("Target Language:", data['target_language'])
print("Translated Text:")
print(data['text'])

## Prompt Template 3: Travelling Guide

In [ ]:
template3 = """ I am travelling to {location}. What are the top 3 things I can do while I am there.
Be very specific and respond as three bullet points """


travel_prompt = PromptTemplate(
    input_variables=["location"],
    template=template3,
)

travel_prompt = travel_prompt.format(location='London')

print(f"LLM Output: {llm(travel_prompt)}")

## Combining LLMs and Prompts in Multi-Step Workflows

In [ ]:
# Chain 1: Tell me about celebrity
first_input_prompt = PromptTemplate(
    input_variables = ['name'],
    template = "Tell me about celebrity {name}"
)
chain1 = LLMChain(
    llm=llm,
    prompt=first_input_prompt,
    output_key='person'
)

# Chain 2: celebrity DOB
second_input_prompt = PromptTemplate(
    input_variables = ['name'],
    template = "when was {name} born"
)
chain2 = LLMChain(
    llm=llm,
    prompt=second_input_prompt,
    output_key='dob'
)

# Chain 3: 5 major events on that day
third_input_prompt = PromptTemplate(
    input_variables = ['dob'],
    template = "Mention 5 major events happened around {dob} in the world"
)
chain3 = LLMChain(
    llm=llm,
    prompt=third_input_prompt,
    output_key='description'
)

#combining chains
from langchain.chains import SequentialChain
celebrity_chain = SequentialChain(
    chains=[chain1,chain2,chain3],
    input_variables=['name'],
    output_variables=['person','dob','description']
)

In [ ]:
data = celebrity_chain({'name':"Justin Timberlake"})
print("Name:", data['name'])
print("Date of Birth:", data['dob'])
print("Description:")
print(data['person'])
print("Historical Events:")
print(data['description'])

## SQL Query Engine

- Creates SQL query from the user input

In [ ]:
class SQLQueryEngine:
    """
    A class representing an SQL query engine.

    Attributes:
        llm (ChatOpenAI): An instance of ChatOpenAI used for natural language processing.
        toolkit (SQLDatabaseToolkit): An SQL database toolkit instance.
        context (dict): Contextual information obtained from the SQL database toolkit.
        tools (list): List of tools available for SQL query execution.
        prompt (ChatPromptTemplate): The prompt used for interactions with the SQL query engine.
        agent_executor (AgentExecutor): An executor for the SQL query engine's agent.
    """
    def __init__(self, model_name, db):
        self.llm = ChatOpenAI(model=model_name, temperature=0)
        self.toolkit = SQLDatabaseToolkit(db=db, llm=self.llm)
        self.context = self.toolkit.get_context()
        self.tools = self.toolkit.get_tools()
        self.prompt = None
        self.agent_executor = None
        
    def set_prompt(self):
        messages = [
            HumanMessagePromptTemplate.from_template("{input}"),
            AIMessage(content=SQL_FUNCTIONS_SUFFIX),
            MessagesPlaceholder(variable_name="agent_scratchpad")
            ]
        self.prompt = ChatPromptTemplate.from_messages(messages)
        self.prompt = self.prompt.partial(**self.context)
        
    def initialize_agent(self):
        agent = create_openai_tools_agent(self.llm, self.tools, self.prompt)
        self.agent_executor = AgentExecutor(
            agent=agent,
            tools=self.toolkit.get_tools(),
            verbose=True,
        )
        
    def get_query_data(self, query):
        if 'return' in query:
            query = query + "\n" + "return percentage is defined as total number of returns divided by total number of orders. You can join orders table with users table to know more about each user"
        return self.agent_executor.invoke({"input": query})['output']

## Python Dashboard Engine

- Creates Streamlit dashboard from data output by SQLQueryEngine

In [ ]:
# REPL -> Read Evaluate Print Loop
class PythonDashboardEngine:
    """
    A class representing a Python dashboard engine.

    Attributes:
        tools (list): A list of tools available for the dashboard engine.
        instructions (str): Instructions guiding the behavior of the dashboard engine.
        prompt (str): The prompt used for interactions with the dashboard engine.
        agent_executor (AgentExecutor): An executor for the dashboard engine's agent.
    """
    def __init__(self):
        self.tools = [PythonREPLTool()]
        self.instructions = """You are an agent designed to write a python code to answer questions.
        You have access to a python REPL, which you can use to execute python code.
        If you get an error, debug your code and try again.
        You might know the answer without running any code, but you should still run the code to get the answer.
        If it does not seem like you can write code to answer the question, just return "I don't know" as the answer.
        Always output the python code only.
        """
        base_prompt = hub.pull("langchain-ai/openai-functions-template")
        self.prompt = base_prompt.partial(instructions=self.instructions)
        self.agent_executor = None
        
    def initialize(self):
        agent = create_openai_functions_agent(ChatOpenAI(model=model_name, temperature=0), self.tools, self.prompt)
        self.agent_executor = AgentExecutor(agent=agent, tools=self.tools, verbose=False)
        
    def get_output(self, query):
        output = self.agent_executor.invoke({"input": "Write a code in python to plot the following data\n\n" + query})
        return output['output']
    
    def parse_output(self, inp):
        inp = inp.split('```')[1].replace("```", "").replace("python", "").replace("plt.show()", "")
        outp = "import streamlit as st\nst.set_option('deprecation.showPyplotGlobalUse', False)\nst.title('E-commerce Company[insights]')\nst.write('Here is our LLM generated dashboard')" \
                + inp + "st.pyplot()\n"
        return outp
    
    def export_to_streamlit(self, data):
        with open("app.py", "w") as text_file:
            text_file.write(self.parse_output(data))

        command = "streamlit run app.py"
        proc = subprocess.Popen([command], shell=True, stdin=None, stdout=None, stderr=None, close_fds=True)

In [ ]:
global sql_query_engine, dashboard_engine

def init_engines():
    sql_query_engine = SQLQueryEngine(model_name, sql_db)
    sql_query_engine.set_prompt()
    sql_query_engine.initialize_agent()

    dashboard_engine = PythonDashboardEngine()
    dashboard_engine.initialize()
    return sql_query_engine, dashboard_engine

### Query 1

- Number of users with their gender

In [ ]:
sql_query_engine, dashboard_engine = init_engines()
query = "Number of users with their gender"
sql_query_engine_output = sql_query_engine.get_query_data(query)
#print(sql_query_engine_output)

dashboard_engine_output = dashboard_engine.get_output(sql_query_engine_output)
dashboard_engine.export_to_streamlit(dashboard_engine_output)

### Query 2

- number of users in each country who came via facebook

In [ ]:
#sql_query_engine, dashboard_engine = init_engines()
query = "number of users in each country who came via facebook"
sql_query_engine_output = sql_query_engine.get_query_data(query)
#print(sql_query_engine_output)

dashboard_engine_output = dashboard_engine.get_output(sql_query_engine_output)
dashboard_engine.export_to_streamlit(dashboard_engine_output)

### Query 3

- number of orders per month since January 2020

In [ ]:
#sql_query_engine, dashboard_engine = init_engines()
query = "number of orders per month since January 2020"
sql_query_engine_output = sql_query_engine.get_query_data(query)
#print(sql_query_engine_output)

dashboard_engine_output = dashboard_engine.get_output(sql_query_engine_output)
dashboard_engine.export_to_streamlit(dashboard_engine_output)

### Query 4

- return percentage country wise

In [ ]:
#sql_query_engine, dashboard_engine = init_engines()
query = "return percentage country wise"
sql_query_engine_output = sql_query_engine.get_query_data(query)
#print(sql_query_engine_output)

dashboard_engine_output = dashboard_engine.get_output(sql_query_engine_output)
dashboard_engine.export_to_streamlit(dashboard_engine_output)

### Query 5

- top 3 product categories with highest number of returns by count

In [ ]:
sql_query_engine, dashboard_engine = init_engines()
query = "top 3 product categories with highest number of returns by count"
sql_query_engine_output = sql_query_engine.get_query_data(query)
#print(sql_query_engine_output)

dashboard_engine_output = dashboard_engine.get_output(sql_query_engine_output)
dashboard_engine.export_to_streamlit(dashboard_engine_output)

### Query 6

- which are my top 5 geographies with highest business

In [ ]:
#sql_query_engine, dashboard_engine = init_engines()
query = "which are my top 5 geographies with highest business"
sql_query_engine_output = sql_query_engine.get_query_data(query)
#print(sql_query_engine_output)

dashboard_engine_output = dashboard_engine.get_output(sql_query_engine_output)
dashboard_engine.export_to_streamlit(dashboard_engine_output)

### Query 7

- which product categories have the highest margins in 2024

In [ ]:
#sql_query_engine, dashboard_engine = init_engines()
query = "which product categories have the highest margins in 2024"
sql_query_engine_output = sql_query_engine.get_query_data(query)
#print(sql_query_engine_output)

dashboard_engine_output = dashboard_engine.get_output(sql_query_engine_output)
dashboard_engine.export_to_streamlit(dashboard_engine_output)

### Query 8

- which are the top 5 cities with highest order cancellation percentage

In [ ]:
#sql_query_engine, dashboard_engine = init_engines()
query = "which are the top 5 cities with highest order cancellation percentage in 2024 but atleast 50 total orders"
sql_query_engine_output = sql_query_engine.get_query_data(query)
#print(sql_query_engine_output)

dashboard_engine_output = dashboard_engine.get_output(sql_query_engine_output)
dashboard_engine.export_to_streamlit(dashboard_engine_output)